export const movieTypes = {
  GET_MOVIES_LOADING: "[MOVIE] GET MOVIES LOADING",
  GET_MOVIES_SUCCESS: "[MOVIE] GET MOVIES SUCCESS",
  GET_MOVIES_ERROR: "[MOVIE] GET MOVIES ERROR",

  GET_FAVORITES_MOVIES_LOADING: "[MOVIE] GET FAVORITES MOVIES LOADING",
  GET_FAVORITES_MOVIES_SUCCESS: "[MOVIE] GET FAVORITES MOVIES SUCCESS",
  GET_FAVORITES_MOVIES_ERROR: "[MOVIE] GET FAVORITES MOVIES ERROR",

  CREATE_FAVORITE_MOVIE_LOADING: "[MOVIE] CREATE FAVORITE MOVIE LOADING",
  CREATE_FAVORITE_MOVIE_SUCCESS: "[MOVIE] CREATE FAVORITE MOVIE SUCCESS",
  CREATE_FAVORITE_MOVIE_ERROR: "[MOVIE] CREATE FAVORITE MOVIE ERROR",

  DELETE_FAVORITE_MOVIE_LOADING: "[MOVIE] DELETE FAVORITE MOVIE LOADING",
  DELETE_FAVORITE_MOVIE_SUCCESS: "[MOVIE] DELETE FAVORITE MOVIE SUCCESS",
  DELETE_FAVORITE_MOVIE_ERROR: "[MOVIE] DELETE FAVORITE MOVIE ERROR",
};
