export const userTypes = {
    USER_CREATE_LOADING : "[USER] CREATE LOADING",
    USER_CREATE_SUCCESS : "[USER] CREATE SUCCESS",
    USER_CREATE_ERROR   : "[USER] CREATE ERROR",

    USER_DELETE_LOADING : "[USER] DELETE LOADING",
    USER_DELETE_SUCCESS : "[USER] DELETE SUCCESS",
    USER_DELETE_ERROR   : "[USER] DELETE ERROR",
}